@startuml
'https://plantuml.com/activity-diagram-beta

start
    :Get output fileName;
    :Create new instance of File;
    while (fileName -> Exists)
        :Ask user to change fileName;

        switch (Answer)
        case (No)
            :Use the fileName provided by default;
        case (Yes)
            :Read new fileName;
            :Assign new fileName to File;
        case (default)
            :Incorrect input, print prompt again;
        endswitch

        if (answer == no) is (Yes) then
            break;
        endif
    endwhile

    if (Is it possible to write into file?) is (Yes) then
        #palegreen:Return File;
        kill
    else (No)
        #pink:Throw exception;
        kill

@enduml
