@startuml
'https://plantuml.com/activity-diagram-beta

start
    :Get Collection of Employee objects;
    :Find max length for each property of Employee;
    while (for each Employee in collection)
        :Convert Employee object into strings;
        :Add them to the output using specific format;
    endwhile

    #palegreen:Return complete output String;
    kill

@enduml
