@startuml
'https://plantuml.com/activity-diagram-beta

start
    :Get Employee object;
    :Get Table format;
    while (for each element in table)
        :Add the columnSpan to the format String;
    endwhile

    :Convert Employee object to String using specific format;
    #palegreen:Return String;
    kill

@enduml
