@startuml
'https://plantuml.com/activity-diagram-beta

start
    :Get employees collection;

    while(for each employee object in employees collection)
        :Compare each object by salary;
        :Add employee object with higher salary above the one with lower;
    endwhile

    :Return sorted employees collection;

@enduml
