@startuml
'https://plantuml.com/class-diagram

class FileManager {
    -String: relativePath;

    +FileManager(relativePath)

    +String: createFolder(folderName)
    +String: createFile(fileName)
}
@enduml