@startuml
'https://plantuml.com/class-diagram

class FileOut implements Out {
    -String: relativePath
    -String: fileName
    -File: file;

    +FileOut(relativePath, fileName)
    +void: close()
}

class ConsoleOut implements Out {
}

interface Out {
    +void: writeLine(String input)
}

@enduml