@startuml
'https://plantuml.com/class-diagram

class Website {
    -String websiteName
    -String authorName
    -HashMap<FolderType, String> additionalFolders

    -Website(String websiteName, String authorName)
    +Website(String websiteName, String authorName, HashMap<FolderType, String> additionalFolders)

    +void addFolder(FolderType folderType, String folderName)
    +HashMap<FolderType, String> getAdditionalFolders()
    +String getAuthor()
    +String getWebsiteName()
}
@enduml