@startuml
'https://plantuml.com/class-diagram

class WebsiteGenerator {
    -Website website
    -String relativePath

    +WebsiteGenerator(Website website, String relativePath)

    +String generateWebsite()
    +String generateFolder(String folderName)
    +String generateIndexFile()

}

@enduml