@startuml
'https://plantuml.com/class-diagram

class NameSorter implements Sorter {
    -names: List<Name>

    -NameSorter()
    +NameSorter(nameCollection: List<Name>)
}

interface Sorter {
    +sort(): List<T>
}

@enduml