@startuml
'https://plantuml.com/class-diagram

class Database<T> {
    -List<T> dbObjects
    -File dbFile
    -Type token

    +Database(File dbFile, Type token)
    +Database(Type token)
    +Database(List<T> objects, Type token)

    +T findObject(String name)
    +void addObject(T obj)
    +void uploadObjectToDb(T obj)
    +List<T> downloadObjectFromDb()
    +List<T> getDbObjects
}
@enduml