@startuml
'https://plantuml.com/class-diagram

class Database<T> {
    -String: dbFileName
    -String: relativePath
    -List<T>: dbObjects
    -Type: dbTypeToken

    +Database(relativePath, dbFileName, dbTypeToken)
    +Database(dbTypeToken)
    +Database(List<T> dbObjects)

    +T: findObject(objName)
    +void: addObject(obj)
    +List<T>: getDbObjects();

    -void: uploadObjectToDb(obj)
    -List<T>: downloadObjectFromDb()
}

@enduml