@startuml
'https://plantuml.com/class-diagram

class File {
    -String: relativePath;
    -String: fileName;

    +File(relativePath, fileName)

    +void: writeLine(input)
    +String: readAllLines()
}

@enduml