@startuml
'https://plantuml.com/class-diagram

class ConsoleIn implements Input {
    +ConsoleIn()

    +void: close()
}

class FileIn implements Input{
    -Scanner: scanner

    +FileIn(relativePath, fileName)

    +String: readAllLines()
    +void: close()
}

interface Input {
    +String: readLine()
}
@enduml