@startuml
'https://plantuml.com/class-diagram

class JsonDeserializer<T> {
    -Database<T> db
    -Type token

    +JsonDeserializer(Type token)
    +List<T> deserialize(String strToParse)
}

@enduml