@startuml
'https://plantuml.com/class-diagram

class JsonDeserializer<T> {
    -Database<T>: db
    -Type: dbTypeToken

    +JsonDeserializer(dbTypeToken)

    +List<T>: deserialize(strToParse)
}

@enduml