@startuml
'https://plantuml.com/class-diagram

class ConsoleOut implements Output {
    +ConsoleOut()
}

class FileOut implements Output {
    -BufferedWriter: bWriter

    +FileOut(relativePath, fileName)

    +close()
}

interface Output {
    void: writeLine(input)
}

@enduml