@startuml
'https://plantuml.com/class-diagram

class Product {
    -String name
    -double price
    -int quantity

    +Product(String name, double price, int quantity)

    +String getName()
    +int getQuantity()
    +double getPrice()

    +boolean equals(Object o)
    +String toString()
}

@enduml