@startuml
'https://plantuml.com/activity-diagram-beta

start
    :Get current object's properties;
    :Get name's properties;

    if (obj.lastname is empty or name.lastname is empty) then
        :throw exception;
    endif

    :Return obj.lastname.compareTo(name.lastname);
@enduml
