@startuml
'https://plantuml.com/activity-diagram-beta

start
    :Get String;
    :Split string using "," delimiter;
    :Collect string into an array;
    :Put Strings into Name object;
    :Return Name object;

@enduml
