@startuml
'https://plantuml.com/activity-diagram-beta

start
    :Get default fileName;
    :Output default fileName into console;

    while(file exists)
        :Output file exists message;
        :Ask if another fileName should be used;

         switch (answer)
         case (yes)
            :Ask for new fileName;
            :Change fileName;
         case (no)
             :Use default fileName;
        endswitch

        if (answer was no)
            break
        endif
    endwhile

    if (answer was yes) then
        :Create new File;

    :Return fileName;

@enduml
