@startuml
'https://plantuml.com/activity-diagram-beta

start
    :Ask for list of names;

    while (true)
        :Read input from console;

        if (input == done)
            break
        else (True)
            :Convert input to Name object;
            :Add Name to the list;

        endif
    endwhile

    :Return list with names;

@enduml
