@startuml
'https://plantuml.com/activity-diagram-beta

start
    while (foreach element in collection)
        #yellow:Compare Element;
        :Add element to new Collection;
    endwhile

    #palegreen:Return sorted Collection;
stop

@enduml
