@startuml
'https://plantuml.com/activity-diagram-beta

start
    :Get name collection;

    while (for each name object in name collection )
        :Format Name to String;
        :Add String to output;
    endwhile

    :Return output;
@enduml
