@startuml
'https://plantuml.com/class-diagram

class OutputName implements Output {
    #names: List<Name>
    #fileName: String

    +OutputName(names: List<Name>, fileName: String)
}

interface Output {
    +write(): void
}
@enduml