@startuml
'https://plantuml.com/activity-diagram-beta

start
    :Get text;
    :Get pattern for a word;

    :Split text on words using pattern;

    while (for each word)
        if (word exist in a hashmap) is (yes) then
            :increment its value;
        else (no)
            :add word to hashmap and set its value to 1;
        endif
    endwhile

    :Return hashmap;

@enduml
