@startuml
'https://plantuml.com/activity-diagram-beta

start
    :Get folder type;
    :Get folder name;
    :Get additionalFolders collection;

    if(folder type already exists in collection)
        :throw exception;
    endif

    if(file name already exists in collection)
        :throw exception;

    :Add folder type and folder name into additionalFolders collection;
@enduml
