@startuml
'https://plantuml.com/activity-diagram-beta

start
    :Get folder name;
    :Get folder path;

    if (folder with such name already exists) then
        :throw an exception;
    endif

    if (create_folder()) is (True) then
        :Return success message;
        kill
    else
        :Return error message;
        kill
    endif
@enduml
