@startuml
'https://plantuml.com/activity-diagram-beta

start
    :Get file name;
    :Ger file path;

    if (file with such name already exists) then
            :throw an exception;
        endif

    if (create_file()) is (True) then
        :Return success message;
        kill
    else
        :Return error message;
        kill
    endif
@enduml
