@startuml
'https://plantuml.com/activity-diagram-beta

start
    :Get folder name;
    :Get folder path;

    :createFolder(folderName) and add status message to output;

    :Return output string;

@enduml
