@startuml
'https://plantuml.com/activity-diagram-beta

start
    :generateFolder(root_folder) and add status message to output;

    while(for each element in additionalFolders)
        :generateFolder(element) and add status message to output;
    endwhile

    :generateIndexFile() and add status message to output;

    :Return output string;
@enduml
