@startuml
'https://plantuml.com/class-diagram

class Employee {
    -String firstName
    -String lastName
    -double salary

    +Employee(String firstName, String lastName, double salary

    +String getLastName()
    +String getFirstName()
    +double getSalary()
}
@enduml