@startuml
'https://plantuml.com/activity-diagram-beta

start
    :Get pattern;
    :Split pattern on two words per string;
    while (for each pair of words)
        :assign first word to pair;
        :assign second word to pair;
        :add pair to Pair Collection;
    endwhile
    :Return collection of pairs;
@enduml
