@startuml
'https://plantuml.com/class-diagram

class ProductDatabase {
    -String: dbFileName
    -String: relativePath
    -List<Product>: products

    +ProductDatabase(relativePath, dbFileName)

    +Product: findProduct(productName)
    +void: addProduct(product)
}

@enduml