@startuml
'https://plantuml.com/activity-diagram-beta

start
    if (findProduct(product)) is (true) then
        :throw exception;
        kill
    endif
    :uploadObjectToDb(product);
    :downloadObjectFromDb();
    :return true;
@enduml
