@startuml
'https://plantuml.com/activity-diagram-beta

start
    :Get object;
    while (for each object in dbObjects)
        if (object name exists in dbObjects) is (Yes) then
            :throw exception;
        endif
    endwhile
    :uploadObjectToDb(object);
@enduml
