@startuml
'https://plantuml.com/activity-diagram-beta

start
    :Get dbFile;

    :Read everything from dbFile into string;
    :Deserialize that string into collection of Objects;

    :Return collection of Objects;

@enduml
