@startuml
'https://plantuml.com/activity-diagram-beta

start
    while (for each object in dbObjects)
        :compare name provided through input with the name ob objects in dbObjects;
        if (names equal) is (True) then
            :Return an object with equal name;
        endif
    endwhile

   if (no object found) then
        :Return null;

@enduml
