@startuml
'https://plantuml.com/activity-diagram-beta

start
    :Get object;

    :Add object to dbObjects collection;
    :Serialize dbObjects collection;
    :Write serialized string into the output file;

@enduml
